### ISSUE TITLE
libcurl not support https

### ISSUE THREAD

**Issue by rivalak** [XiongGuiHui/My-Linux-config#4]
![wechat image_20181117162855](https://user-images.githubusercontent.com/42036026/48658996-e77bcb80-ea85-11e8-9883-25e36d55f01c.png)

**Comment by Martins3** [comment]
Make sure you have installed all the prerequisites correctly.
https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites

**Comment by rivalak** [comment]
![deepinscreenshot_select-area_20181117164412](https://user-images.githubusercontent.com/42036026/48659171-0da26b00-ea88-11e8-8b15-ee37760332ba.png)

Another issues...

**Comment by Martins3** [comment]
download the source code in zip format instead of `git clone`
