### ISSUE TITLE
Make translate-shell speak works

### ISSUE THREAD

**Issue by rivalak** [XiongGuiHui/My-Linux-config#5]
When we want to output the pronunciation of a word, we can input :
> $ trans -sp word

But you may get the __WARNING__ as below shows : 
![deepinscreenshot_select-area_20181119235044](https://user-images.githubusercontent.com/42036026/48718281-0761e980-ec56-11e8-89f1-0eed68332587.png)

Solution :
> $ sudo apt-get install espeak

**Comment by Martins3** [comment]
In `manjaro`, there is no such warning. However thanks for your anticipation and contribution.
@rivalak  you seems like use the image instead of text for representing warnings or errors, which makes fuzzy search impossible.

**Comment by rivalak** [comment]
Ok, get it.
